---
# handlers file for web

- name: liberar firewall http
  firewalld:
   service: http
   permanent: true
   state: enabled

- name: reload firewall
  service:
   name: firewalld
   state: restarted



