- name: Instalando pacotes no Debian
  package:
   name:
    - apache2
    - php
    - mariadb-server
   state: present
   update_cache: yes

- name: Iniciando o servico Apache
  service:
   name: apache2
   state: started
   enabled: yes

